### ISSUE TITLE
Gedrag afhandelen Event

### ISSUE THREAD

**Issue by SonnyBA** [VNG-Realisatie/notificatieservices#10]
Voor mij is onduidelijk welk gedrag er verwacht wordt wanneer een `Event` wordt ontvangen in de volgende scenario's:

- `Event` heeft geen `domain` en `subscription` velden gespecificeerd
- `Event` heeft geen `domain` maar wel een `subscription` veld gespecificeerd
- `Event` heeft wel een `domain` veld gespecificeerd maar geen `subscription`
- `Event` heeft zowel een `domain` als een `subscription` veld gespecificeerd

Uiteindelijk zullen er meer scenario's zijn (omdat filtering niet in een eerste versie geimplenteerd zal worden) maar volgens mij zijn dit de scenario's die dan overblijven. Het lijkt mij dat in het laatste scenario dat er alleen een `Event` wordt gestuurd wanneer het opgegeven `domain` gekoppeld is aan de opgegeven `subscription`.

**Comment by HenriKorver** [comment]
@Rateotg Heb jij hier al concrete ideeën over?

**Comment by HenriKorver** [comment]
Er zijn raakvlakken met deze discussie: 

https://teams.microsoft.com/l/message/19:8pNyHnpANESETP8z7E2e5lGRzv43U7tKsufMyEvzZMk1@thread.tacv2/1651586450160?tenantId=6ef029ab-3fd7-4d98-9b0e-d1f5fedea6d1&groupId=1e4b61b4-3186-4943-8690-edd294f9415e&parentMessageId=1651586450160&teamName=Referentie-implementatie%20Notificatie%20API&channelName=Algemeen&createdTime=1651586450160

**Comment by Rateotg** [comment]
Ik geloof niet dat het handig is dit via een issue te doen. De vraag is me onduidelijk en doet vermoeden dat we niet hetzelfde lezen in de specificatie (die mogelijk dus niet duidelijk genoeg is).

**Comment by SonnyBA** [comment]
Bij deze even een opsomming van wat er verwacht wordt in de verschillende scenario's:
- Event heeft geen domain en subscription velden gespecificeerd                                                                                
    - Doorsturen naar alle subscriptions zonder domain                              
- Event heeft geen domain en maar wel subscription veld gespecificeerd              
    - Doorsturen naar alle subscriptions zonder domain                              
- Event heeft wel domain maar geen subscription veld gespecificeerd                 
    - Doorsturen naar alle subscription gekoppeld aan dat domain                    
- Event domain en geen subscription                                                 
  - Moet naar alle subscriptions gestuurd worden gekoppeld aan dat domain
