### ISSUE TITLE
Foutmeldingen correct implementeren

### ISSUE THREAD

**Issue by marcdenengelsman** [VNG-Realisatie/notificatieservices#103]
Als sink niet benaderbaar is bij posten abonnement, komt er foutmelding 500 (en als sink als status 200 teruggeeft, komt eveneens foutmelding 500)

**Comment by SonnyBA** [comment]
@marcdenengelsman @Rateotg @HenriKorver de server die deze SSL certificaat gebruikt is niet toegangkelijk door de gebruikers, we zouden dit voor de fieldlab in de applicatie uit kunnen schakelen (de SSL certificaat verificatie), wat zouden jullie hiervan vinden?

**Comment by SonnyBA** [comment]
Dit moeten we aan het einde van het Fieldlab weer even terug zetten.
