### ISSUE TITLE
Hosted (test) version opzetten van de referentie-implementatie

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/notificatieservices#11]
zodat de teamleden (Jeanot, Ad, ik, etc.) de Notificatie API alvast mee kunnen testen  voordat deze op het API Lab gelanceerd wordt.

**Comment by michielverhoef** [comment]
Is de nieuwe versie zetten op testomgeving: https://notificaties-api.test.vng.cloud/api/v1/schema/
