### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/notificatieservices#14]
Analoog aan de tutorial van de ZGW Notificatie API: 

https://github.com/VNG-Realisatie/gemma-zaken/blob/e972e97f5505d226890f6d8ba79a1da9e292717d/docs/_content/ontwikkelaars/handleidingen-en-tutorials/notificeren.md

Hiervoor zijn issues: #11, #12 en #13 essentiële input.

- Uitleggen hoe je username/password via subscriptions.protocolSettings.headers... alsnog kunt doen
- Keuze: niet expliciet via SinkCredentials (plain access token)
- Uitleggen hoe sink validatie werkt
- Basaal: 
- - /domains POST
- - /subscriptions POST
- - /events POST
- ontvangst?

**Comment by michielverhoef** [comment]
Wederom, scope creep dreigt.

**Comment by HenriKorver** [comment]
@Rateotg @marcdenengelsman Ik heb de tutorial van ZGW gekopieerd naar [hier](https://github.com/VNG-Realisatie/notificatieservices/edit/main/docs/api-specification/api-lab/tutorial.md) zodat het als basis gebruikt kan worden voor onze eigen tutorial.

**Comment by HenriKorver** [comment]
@marcdenengelsman Jij ging toch de tutorial schrijven?

**Comment by marcdenengelsman** [comment]
@HenriKorver : Inderdaad, ik ga daar morgen verder mee aan de slag! Ik weet alleen niet of ik daar ook het docket-stuk in ga opnemen, omdat we dat eigenlijk niet gaan ondersteunen in het API-Lab.

**Comment by HenriKorver** [comment]
> Ik weet alleen niet of ik daar ook het docker-stuk in ga opnemen, omdat we dat eigenlijk niet gaan ondersteunen in het API-Lab.

Eens, dat heeft inderdaad geen prio voor het API-lab.
