### ISSUE TITLE
OAS non-empty construct beoordelen en consequent doorvoeren

### ISSUE THREAD

**Issue by Rateotg** [VNG-Realisatie/notificatieservices#20]
Waarschijnlijk zit dit construct ofwel alleen in subscriptions van CE of in ZGW en is dat gekopieerd naar events en mogelijk domains.

**Comment by Rateotg** [comment]
Check met NRC van ZGW gedaan. Daarin komt het meta attribuut nullable niet voor. Voorstel is de API gelijk te houden aan de huidige ZGW conventie.

**Comment by HenriKorver** [comment]
Velden die een minLength 1 hebben worden in Redoc  weergegeven als `non-empty` wat prima is. Wel heb ik bij alle optionele velden (lees: velden die niet verplicht zijn) `nullable`  gemaakt conform de [json specificatie van CE](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/cloudevents.json).

**Comment by HenriKorver** [comment]
@SonnyBA Dit heeft consequenties voor  de referentie-implementatie!
