### ISSUE TITLE
Is filters attribuut in de subscriptions resource goed gedeclareerd?

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/notificatieservices#3]
Dit attribuut is recursief. In de oorspronkelijke spec van CE stond bij ieder subtype van filter steeds: $ref: "#/components/schemas/Filter". Dit is weggehaald omdat deze constructie onduidelijk was. De vraag is wat de bedoeling is van deze constructie en of we deze weer moeten herstellen?

**Comment by HenriKorver** [comment]
@Rateotg Bij nadere bestudering denk ik de constructie te begrijpen. Het schema object `Filter` wordt gebruikt als super type voor alle andere filters zoals `AllFilter`, `AnyFilter`, etc.  Hoewel `Filter` geen properties heeft worden wel zijn titel en beschrijving overgeërfd naar alle subtypes ( `AllFilter`, `AnyFilter`, etc.) door middel van de AllOf-constructie. Ik weet niet of dit veel toegevoegde waarde heeft en of code-generatoren zich erop stuk zullen bijten, maar de CE-architecten vonden dit blijkbaar een nette manier van modelleren.
Ik zou de constructie het liefst weer in ere hersteld zien om zo dicht mogelijk bij de orginele OAS te blijven.

**Comment by Rateotg** [comment]
Volledige specificatie van CE teruggezet.
