### ISSUE TITLE
ZGW documentatielink inhoudelijk omzetten naar nieuwe API

### ISSUE THREAD

**Issue by marcdenengelsman** [VNG-Realisatie/notificatieservices#56]
Zie: https://github.com/vng-Realisatie/zaken-api/blob/1.2.0/src/notificaties.md

Zelfde inhoud maken maar dan voor nieuwe API.

**Comment by Rateotg** [comment]
Er is een nieuwe pagina aangemaakt voor het Zaken domein als voorbeeld:
https://github.com/VNG-Realisatie/notificatieservices/blob/main/docs/api-specification/voorbeeld_documentatielink_zaken_domein.md
Er is een beperkt aantal resources/acties omgezet in eventtypes. Moet nog afgemaakt en beoordeeld worden. Zie toelichting kolom in de tabel met eventtypes voor vraagstukken bij omzetting.
