### ISSUE TITLE
`/domains` en `/subscription` resources hebben geen PATCH-operatie. Waarom?

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/notificatieservices#6]
In ZGW heeft `/abonnementen` namelijk wel een PATCH-operatie.

**Comment by HenriKorver** [comment]
@Rateotg Kun je nog even kijken naar deze vraag?

**Comment by Rateotg** [comment]
Wat betreft de domains resource lijkt met functioneel gezien de mogelijkheid om te kunnen wijzigen wel nodig. Meest minimale functionaliteit volstaat daarbij voorlopig. Kan jij knoop doorhakken of je dan liever voor PUT, PATCH of beiden kiest?
