### ISSUE TITLE
`/domains` resource heeft PUT en DELETE operaties, `/kanaal` in ZGW API heeft dat niet. Waarom dit verschil?

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/notificatieservices#7]

**Comment by HenriKorver** [comment]
@Rateotg Kun je nog even kijken naar deze vraag?

**Comment by Rateotg** [comment]
Het lijkt me dat er beheer mogelijk moet zijn op domains/kanalen. Vandaar de DELETE en een PUT en/of PATCH. Vragen mogelijk wel om bijzondere autorisaties. Nog wel de vraag of PUT of PATCH nodig is. Wat is het meest gebruikelijk als minimale variant?

**Comment by HenriKorver** [comment]
Omdat ZGW geen PUT en DELETE ondersteunt op kanalen zou ik dit op domains voorlopig ook niet doen en wachten we op een userstory. 
@SonnyBA: Operaties PUT en DELETE voor domains hoeft nog niet geïmplementeerd te worden.
