### ISSUE TITLE
OAS: Client API spec check resource path

### ISSUE THREAD

**Issue by Rateotg** [VNG-Realisatie/notificatieservices#71]
- Webhooks path is uitgecommentarieerd, bewust?

**Comment by HenriKorver** [comment]
@Rateotg Ik heb de webhooks path weer teruggezet omdat je dan helemaal vrij bent om het endpoint te kiezen waarop je als consumer de events wilt ontvangen.  In de vorige versie van de OAS was men verplicht het endpoint te laten eindigen op  `/events` wat een onnodige (en onhandige) restrictie is.
