### ISSUE TITLE
Openstaande vragen specificatie

### ISSUE THREAD

**Issue by SonnyBA** [VNG-Realisatie/notificatieservices#8]
Tijdens het implementeren van de specificatie zijn er een aantal vragen bij me ontstaan:

- In het [gedrag.md document van de specificatie](https://github.com/VNG-Realisatie/notificatieservices/blob/main/docs/api-specification/gedrag.md#2-event-klaarmaken-voor-aflevering) wordt aangegeven (in stap 2) dat het `subscription​` veld ingevuld moet worden met "het id van de subscription van de afnemer", waar zou deze waarde vandaan gehaald moeten worden?
- Dezelfde vraag komt op bij het `subscriberReference​,` de waarde waarmee dit veld gevuld zou moeten worden, waar zou deze te vinden moeten zijn?
- In de [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/notificatieservices/main/docs/api-specification/notifications.yaml) zie ik daarnaast camelcase attributen en attributen met underscores voorbij komen (bijvoorbeeld `data_base64` bij `Event` en `protocolSettings` bij `Subscription`), het lijkt mij dat we hier consistent in willen zijn en willen gaan voor camelcase?

**Comment by michielverhoef** [comment]
Ik heb dit issue toegewezen aan Henri als PO.

**Comment by SonnyBA** [comment]
Ik heb daarnaast nog een vraag wat betreft het gedrag van de bestaande notificatie API. [In de bestaande API ](https://github.com/VNG-Realisatie/notificaties-api/blob/master/src/nrc/api/validators.py#L10) wordt er gevalideerd of de opgegeven `callbackUrl` (in de nieuwe versie het `sink` attribuut) een valide URL is welke notificaties kan ontvangen door er een soort "dummy" notificatie ernaar te versturen. Is dit gedrag wat we mee willen nemen naar de nieuwe versie?

**Comment by Rateotg** [comment]
subscription veld:
Als een event binnen is gekomen moet deze doorgestuurd worden aan alle afnemers die deze willen ontvangen. Om te bepalen naar wie het event doorgestuurd moet worden lopen we alle subscriptions langs (conceptueel algoritme, technisch gaat dit wellicht anders). Als het event voldoet aan de filtercriteria van de subscription (source, domain, types en filters) dan sturen we het event door aan de afnemer die hoort bij de subscription (door een POST te doen op de sink in de subscription). Tijdens die POST moet het subscription attribuut in het event de waarde hebben/krijgen van het id van de subscription waar we mee bezig zijn. We vullen bij het 'doorsturen' dus steeds het subscription id in van de subscription waaraan het event voldoet (filtering) en waarvan we de sink gebruiken om het event met een POST af te leveren.

**Comment by Rateotg** [comment]
subscribersReference veld:
Dit veld heeft de afnemer kunnen opgeven bij het maken van de subscription (POST op subscription resource). Het moet dus bij het aanmaken opgeslagen worden en net zoals het subscription id bij het doorsturen in het event ingevuld worden (zie beschrijving over subscription hierboven).

**Comment by Rateotg** [comment]
casing van attributen:
De casing van attributen is nog een puzzel. Officieel laat CE geen underscores en geen camelcase toe! Maar in de CE community zien we dus al diverse uitzonderingen. De CE json uitwerking komen we data_base64 tegen (dat attribuut is dus conform spec) en in de subscription OAS uitwerking komen we diverse attributen met camelcase tegen (die zijn dus ook volgens draft spec). We hebben dit als bespreekpunt staan in het team. Maar is nog niet zo heel eenvoudig om hier een goede keuze in te maken. Voorlopig dus het meest veilig om alles conform CE spec te laten.

**Comment by Rateotg** [comment]
verificatie callback url:
Het is inderdaad wel wenselijk deze verificatie in te gaan bouwen conform CE specificatie.

**Comment by HenriKorver** [comment]
> subscribersReference veld:
Dit veld heeft de afnemer kunnen opgeven bij het maken van de subscription (POST op subscription resource). Het moet dus bij het aanmaken opgeslagen worden en net zoals het subscription id bij het doorsturen in het event ingevuld worden (zie beschrijving over subscription hierboven).

`subscribersReference` veld zit nog niet in de OAS! Moet dus eerst nog worden toegevoegd. Ja toch?

**Comment by HenriKorver** [comment]
En hoe gaan we het veld `subscribersReference` toevoegen? Als een nieuw attribuut van de subsciption resource of als name/value pair binnen het config attribute van CE. Met de eerste optie verander je de oorspronkelijke Subscription OAS van CE en lijkt me daarom minder wenselijk.

**Comment by HenriKorver** [comment]
@SonnyBA Graag de volgende keer voor elke vraag een apart issue indienen. Dat werkt wat makkelijker :-)
