### ISSUE TITLE
OAS & RI: Aanpassen http statuscodes

### ISSUE THREAD

**Issue by Rateotg** [VNG-Realisatie/notificatieservices#88]
In OAS bij /events post alleen een 200 code teruggeven.

In Client OAS bij /events post alleen de 204 code teruggeven. Let hierbij op: In de response header GEEN location meegeven.

**Comment by HenriKorver** [comment]
@SonnyBA Aanpassingen doorgevoerd in de twee OAS'en. Jij kunt de aanpassingen nu doorvoeren in de RI.
