### ISSUE TITLE
OAS: Subscription resource weer gelijkmaken aan CE spec (let op details)

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/notificatieservices#9]
Subscription id staat nu vooraan in plaats van achteraan zoals in de oospronkelijke OAS van CE

Dit is verwarrend en het zou wenselijk zijn zoveel  mogelijk de originele OAS te volgen. Mijn voorstel is dat de originele OAS van CE als basis wordt genomen en daarop alleen verbijzonderingen mogen worden doorgevoerd die backwards compatible zijn.  Dit doen we dan met uitcommentariëren zodat de verschillen expliciet zichtbaar zijn.

**Comment by Rateotg** [comment]
Mee eens.
