### ISSUE TITLE
RefImpl: uuid exposen bij domains

### ISSUE THREAD

**Issue by marcdenengelsman** [VNG-Realisatie/notificatieservices#98]

**Comment by SonnyBA** [comment]
@marcdenengelsman @Rateotg @HenriKorver ik stel voor dat we dit achterwegen laten omdat we waarschijnlijk voor dezelfde redenen het `url` veld hebben toegevoegd. Ik stel wel voor om dit ook gelijk te trekken in de `Subscription`; het toevoegen van een read-only `url` veld waarop een specifieke `Subscription` terug te vinden is, de `Subscription` heeft dit namelijk nog niet.
